const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '..', '.env') });
const mongoose = require('mongoose');
const Scheme = require('../models/Scheme');
const logger = require('../utils/logger');

const schemes = [
    {
        name_en: 'Mahatma Jyotirao Phule Jan Arogya Yojana',
        name_mr: 'महात्मा ज्योतिराव फुले जन आरोग्य योजना',
        name_hi: 'महात्मा ज्योतिराव फुले जन आरोग्य योजना',
        ministry: 'Maharashtra Health Department',
        level: 'state',
        category: ['health'],
        eligibility: {
            age_min: 0, age_max: 120, gender: 'all',
            income_limit_annual: 200000, caste: ['all'],
            bpl_required: false, residence: 'maharashtra',
        },
        benefit_description: 'Health insurance coverage up to ₹5 lakh per year for treatment in government and empanelled hospitals.',
        benefit_amount: '₹5,00,000 per year',
        documents_required: ['Aadhaar Card', 'Ration Card', 'Income Certificate', 'Domicile Certificate'],
        apply_link: 'https://jeevandayee.gov.in',
        active: true,
    },
    {
        name_en: 'PM Kisan Samman Nidhi Yojana',
        name_mr: 'पीएम किसान सन्मान निधी योजना',
        name_hi: 'पीएम किसान सम्मान निधि योजना',
        ministry: 'Ministry of Agriculture & Farmers Welfare',
        level: 'central',
        category: ['agriculture', 'finance'],
        eligibility: {
            age_min: 18, age_max: 120, gender: 'all',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: false, residence: 'india',
            occupation: ['farmer'],
        },
        benefit_description: 'Direct income support of ₹6,000 per year to all landholding farmer families in three equal instalments.',
        benefit_amount: '₹6,000 per year (₹2,000 per instalment)',
        documents_required: ['Aadhaar Card', '7/12 Land Record', 'Bank Account Passbook'],
        apply_link: 'https://pmkisan.gov.in',
        active: true,
    },
    {
        name_en: 'Ladki Bahin Yojana',
        name_mr: 'लाडकी बहीण योजना',
        name_hi: 'लाडकी बहन योजना',
        ministry: 'Women and Child Development Department, Maharashtra',
        level: 'state',
        category: ['women', 'finance'],
        eligibility: {
            age_min: 21, age_max: 65, gender: 'female',
            income_limit_annual: 250000, caste: ['all'],
            bpl_required: false, residence: 'maharashtra',
        },
        benefit_description: 'Monthly financial assistance of ₹1,500 per month to economically weaker women of Maharashtra.',
        benefit_amount: '₹1,500 per month',
        documents_required: ['Aadhaar Card', 'Ration Card', 'Income Certificate', 'Bank Account', 'Domicile Certificate'],
        apply_link: 'https://ladakibahin.maharashtra.gov.in',
        active: true,
    },
    {
        name_en: 'Rajshri Shahu Maharaj Scholarship',
        name_mr: 'राजश्री छत्रपती शाहू महाराज शिष्यवृत्ती',
        name_hi: 'राजश्री शाहू महाराज छात्रवृत्ति',
        ministry: 'Social Justice Department, Maharashtra',
        level: 'state',
        category: ['education'],
        eligibility: {
            age_min: 17, age_max: 30, gender: 'all',
            income_limit_annual: 600000, caste: ['obc', 'nt', 'vjnt'],
            bpl_required: false, residence: 'maharashtra',
        },
        benefit_description: 'Scholarship for OBC, NT, and VJNT students pursuing higher education. Covers tuition fees and maintenance allowance.',
        benefit_amount: 'Up to ₹2,50,000 per year based on course',
        documents_required: ['Aadhaar Card', 'Caste Certificate', 'Non-Creamy Layer Certificate', 'Income Certificate', 'Marksheet', 'Admission Letter'],
        apply_link: 'https://mahadbt.maharashtra.gov.in',
        active: true,
    },
    {
        name_en: 'Dr. Babasaheb Ambedkar SC/ST Scholarship',
        name_mr: 'डॉ. बाबासाहेब आंबेडकर अनुसूचित जाती/जमाती शिष्यवृत्ती',
        name_hi: 'डॉ. बाबासाहेब अम्बेडकर SC/ST छात्रवृत्ति',
        ministry: 'Social Justice Department, Maharashtra',
        level: 'state',
        category: ['education'],
        eligibility: {
            age_min: 17, age_max: 35, gender: 'all',
            income_limit_annual: 250000, caste: ['sc', 'st'],
            bpl_required: false, residence: 'maharashtra',
        },
        benefit_description: 'Post-matric scholarship for SC/ST students covering tuition fees, maintenance allowance, and study material.',
        benefit_amount: 'Full tuition fee + ₹1,200 to ₹3,000 per month maintenance',
        documents_required: ['Aadhaar Card', 'Caste Certificate', 'Income Certificate', 'Admission Letter', 'Bank Account'],
        apply_link: 'https://mahadbt.maharashtra.gov.in',
        active: true,
    },
    {
        name_en: 'PM Awas Yojana Gramin (PMAY-G)',
        name_mr: 'पंतप्रधान आवास योजना ग्रामीण',
        name_hi: 'प्रधानमंत्री आवास योजना ग्रामीण',
        ministry: 'Ministry of Rural Development',
        level: 'central',
        category: ['housing'],
        eligibility: {
            age_min: 18, age_max: 120, gender: 'all',
            income_limit_annual: 120000, caste: ['all'],
            bpl_required: true, residence: 'india',
        },
        benefit_description: 'Financial assistance to BPL households for construction of pucca houses with basic amenities in rural areas.',
        benefit_amount: '₹1,20,000 (plain areas) / ₹1,30,000 (hilly/difficult areas)',
        documents_required: ['Aadhaar Card', 'BPL Certificate', 'Land Documents', 'Bank Account', 'SECC-2011 Data'],
        apply_link: 'https://pmayg.nic.in',
        active: true,
    },
    {
        name_en: 'Atal Pension Yojana (APY)',
        name_mr: 'अटल पेन्शन योजना',
        name_hi: 'अटल पेंशन योजना',
        ministry: 'Ministry of Finance, Pension Fund Regulatory Authority',
        level: 'central',
        category: ['pension', 'finance'],
        eligibility: {
            age_min: 18, age_max: 40, gender: 'all',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: false, residence: 'india',
        },
        benefit_description: 'Guaranteed pension scheme for unorganised sector workers. Pension of ₹1,000 to ₹5,000 per month after age 60.',
        benefit_amount: '₹1,000 to ₹5,000 per month after 60',
        documents_required: ['Aadhaar Card', 'Bank Account (savings)', 'Mobile Number'],
        apply_link: 'https://npscra.nsdl.co.in/scheme-apy.php',
        active: true,
    },
    {
        name_en: 'PM Ujjwala Yojana',
        name_mr: 'पंतप्रधान उज्ज्वला योजना',
        name_hi: 'प्रधानमंत्री उज्ज्वला योजना',
        ministry: 'Ministry of Petroleum and Natural Gas',
        level: 'central',
        category: ['women', 'health'],
        eligibility: {
            age_min: 18, age_max: 120, gender: 'female',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: true, residence: 'india',
        },
        benefit_description: 'Free LPG connection to women from BPL households to reduce dependence on traditional cooking fuels.',
        benefit_amount: 'Free LPG connection + first refill subsidy',
        documents_required: ['Aadhaar Card', 'BPL Ration Card', 'Bank Account', 'Passport Photo'],
        apply_link: 'https://pmuy.gov.in',
        active: true,
    },
    {
        name_en: 'PM Mudra Yojana (PMMY)',
        name_mr: 'पंतप्रधान मुद्रा योजना',
        name_hi: 'प्रधानमंत्री मुद्रा योजना',
        ministry: 'Ministry of Finance',
        level: 'central',
        category: ['employment', 'finance'],
        eligibility: {
            age_min: 18, age_max: 65, gender: 'all',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: false, residence: 'india',
        },
        benefit_description: 'Collateral-free loans for non-farm micro/small enterprises. Shishu: up to ₹50,000; Kishore: ₹50,000–5 lakh; Tarun: ₹5–10 lakh.',
        benefit_amount: 'Up to ₹10,00,000 loan',
        documents_required: ['Aadhaar Card', 'PAN Card', 'Business Plan', 'Bank Account', 'Address Proof'],
        apply_link: 'https://www.mudra.org.in',
        active: true,
    },
    {
        name_en: 'Swadhar Greh Scheme',
        name_mr: 'स्वाधार गृह योजना',
        name_hi: 'स्वाधार गृह योजना',
        ministry: 'Ministry of Women and Child Development',
        level: 'central',
        category: ['women', 'housing'],
        eligibility: {
            age_min: 18, age_max: 120, gender: 'female',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: false, residence: 'india',
            marital_status: ['widow', 'divorced'],
        },
        benefit_description: 'Shelter, food, clothing, and rehabilitation to women in difficult circumstances including widows, domestic violence victims, and destitute women.',
        benefit_amount: 'Free shelter, food, clothing, legal aid',
        documents_required: ['Aadhaar Card', 'Any identity proof', 'FIR copy (if applicable)'],
        apply_link: 'https://wcd.nic.in/schemes/swadhar-greh',
        active: true,
    },
    {
        name_en: 'National Scholarship Portal — Post Matric',
        name_mr: 'राष्ट्रीय शिष्यवृत्ती पोर्टल — पोस्ट मॅट्रिक',
        name_hi: 'राष्ट्रीय छात्रवृत्ति पोर्टल — पोस्ट मैट्रिक',
        ministry: 'Ministry of Education, Government of India',
        level: 'central',
        category: ['education'],
        eligibility: {
            age_min: 17, age_max: 35, gender: 'all',
            income_limit_annual: 250000, caste: ['sc', 'st', 'obc'],
            bpl_required: false, residence: 'india',
        },
        benefit_description: 'Post-matric scholarship for minority and SC/ST/OBC students pursuing studies beyond Class 10.',
        benefit_amount: '₹5,000 to ₹20,000 per year depending on course',
        documents_required: ['Aadhaar Card', 'Caste Certificate', 'Income Certificate', 'Previous Marksheet', 'Bank Account'],
        apply_link: 'https://scholarships.gov.in',
        active: true,
    },
    {
        name_en: 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)',
        name_mr: 'इंदिरा गांधी राष्ट्रीय वृद्धापकाळ निवृत्तीवेतन योजना',
        name_hi: 'इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना',
        ministry: 'Ministry of Rural Development',
        level: 'central',
        category: ['pension', 'elderly'],
        eligibility: {
            age_min: 60, age_max: 120, gender: 'all',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: true, residence: 'india',
        },
        benefit_description: 'Monthly pension for BPL elderly citizens. ₹200/month for age 60–79 and ₹500/month for age 80 and above.',
        benefit_amount: '₹200 to ₹500 per month',
        documents_required: ['Aadhaar Card', 'Age Proof', 'BPL Certificate', 'Bank Account'],
        apply_link: 'https://nsap.nic.in',
        active: true,
    },
    {
        name_en: 'Indira Gandhi National Widow Pension Scheme (IGNWPS)',
        name_mr: 'इंदिरा गांधी राष्ट्रीय विधवा निवृत्तीवेतन योजना',
        name_hi: 'इंदिरा गांधी राष्ट्रीय विधवा पेंशन योजना',
        ministry: 'Ministry of Rural Development',
        level: 'central',
        category: ['women', 'pension'],
        eligibility: {
            age_min: 40, age_max: 79, gender: 'female',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: true, residence: 'india',
            marital_status: ['widow'],
        },
        benefit_description: 'Monthly pension of ₹300 for BPL widows aged 40–79 years.',
        benefit_amount: '₹300 per month',
        documents_required: ['Aadhaar Card', 'Husband Death Certificate', 'BPL Certificate', 'Bank Account'],
        apply_link: 'https://nsap.nic.in',
        active: true,
    },
    {
        name_en: 'Soil Health Card Scheme',
        name_mr: 'मृद आरोग्य कार्ड योजना',
        name_hi: 'मृदा स्वास्थ्य कार्ड योजना',
        ministry: 'Ministry of Agriculture & Farmers Welfare',
        level: 'central',
        category: ['agriculture'],
        eligibility: {
            age_min: 18, age_max: 120, gender: 'all',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: false, residence: 'india',
            occupation: ['farmer'],
        },
        benefit_description: 'Free soil health card to farmers providing information on nutrient status of their soil and recommendations on fertilisers.',
        benefit_amount: 'Free service',
        documents_required: ['Aadhaar Card', 'Land Record (7/12)'],
        apply_link: 'https://soilhealth.dac.gov.in',
        active: true,
    },
    {
        name_en: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
        name_mr: 'प्रधानमंत्री पीक विमा योजना',
        name_hi: 'प्रधानमंत्री फसल बीमा योजना',
        ministry: 'Ministry of Agriculture & Farmers Welfare',
        level: 'central',
        category: ['agriculture', 'finance'],
        eligibility: {
            age_min: 18, age_max: 120, gender: 'all',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: false, residence: 'india',
            occupation: ['farmer'],
        },
        benefit_description: 'Crop insurance scheme providing financial support to farmers suffering crop loss due to unforeseen events like drought, flood, and pest attacks.',
        benefit_amount: 'As per crop loss assessment',
        documents_required: ['Aadhaar Card', 'Land Record (7/12)', 'Bank Account', 'Sowing Certificate'],
        apply_link: 'https://pmfby.gov.in',
        active: true,
    },
    {
        name_en: 'Disability Pension Scheme Maharashtra',
        name_mr: 'अपंग निवृत्तीवेतन योजना महाराष्ट्र',
        name_hi: 'विकलांग पेंशन योजना महाराष्ट्र',
        ministry: 'Social Justice Department, Maharashtra',
        level: 'state',
        category: ['disability', 'pension'],
        eligibility: {
            age_min: 18, age_max: 120, gender: 'all',
            income_limit_annual: 50000, caste: ['all'],
            bpl_required: false, residence: 'maharashtra',
            disability_required: true,
        },
        benefit_description: 'Monthly financial assistance to persons with 40% or more disability who are below poverty line in Maharashtra.',
        benefit_amount: '₹600 per month',
        documents_required: ['Aadhaar Card', 'Disability Certificate (40%+)', 'Income Certificate', 'Domicile Certificate', 'Bank Account'],
        apply_link: 'https://sjsa.maharashtra.gov.in',
        active: true,
    },
    {
        name_en: 'Ramai Awas Gharkul Yojana',
        name_mr: 'रमाई आवास घरकुल योजना',
        name_hi: 'रमाई आवास घरकुल योजना',
        ministry: 'Social Justice Department, Maharashtra',
        level: 'state',
        category: ['housing', 'education'],
        eligibility: {
            age_min: 18, age_max: 120, gender: 'all',
            income_limit_annual: 100000, caste: ['sc', 'st'],
            bpl_required: true, residence: 'maharashtra',
        },
        benefit_description: 'Free house construction assistance for SC/ST BPL families in Maharashtra who are homeless.',
        benefit_amount: '₹1,50,000 for house construction',
        documents_required: ['Aadhaar Card', 'Caste Certificate', 'BPL Certificate', 'Land Documents or NOC', 'Bank Account'],
        apply_link: 'https://sjsa.maharashtra.gov.in',
        active: true,
    },
    {
        name_en: 'Savitribai Phule Scholarship for Girls',
        name_mr: 'सावित्रीबाई फुले शिष्यवृत्ती',
        name_hi: 'सावित्रीबाई फुले छात्रवृत्ति',
        ministry: 'School Education Department, Maharashtra',
        level: 'state',
        category: ['education', 'women'],
        eligibility: {
            age_min: 10, age_max: 18, gender: 'female',
            income_limit_annual: 100000, caste: ['sc', 'st', 'obc', 'nt', 'vjnt'],
            bpl_required: false, residence: 'maharashtra',
        },
        benefit_description: 'Scholarship to prevent school dropout of girls from economically weaker sections in Classes 5 to 10.',
        benefit_amount: '₹1,800 per year',
        documents_required: ['Aadhaar Card', 'Caste Certificate', 'Income Certificate', 'School Enrolment Certificate'],
        apply_link: 'https://mahadbt.maharashtra.gov.in',
        active: true,
    },
    {
        name_en: 'Ayushman Bharat PM-JAY',
        name_mr: 'आयुष्मान भारत पंतप्रधान जन आरोग्य योजना',
        name_hi: 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना',
        ministry: 'Ministry of Health and Family Welfare',
        level: 'central',
        category: ['health'],
        eligibility: {
            age_min: 0, age_max: 120, gender: 'all',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: true, residence: 'india',
        },
        benefit_description: 'World\'s largest health insurance scheme providing coverage up to ₹5 lakh per family per year for secondary and tertiary care hospitalization.',
        benefit_amount: '₹5,00,000 per family per year',
        documents_required: ['Aadhaar Card', 'Ration Card', 'SECC-2011 inclusion proof'],
        apply_link: 'https://pmjay.gov.in',
        active: true,
    },
    {
        name_en: 'Sukanya Samriddhi Yojana',
        name_mr: 'सुकन्या समृद्धी योजना',
        name_hi: 'सुकन्या समृद्धि योजना',
        ministry: 'Ministry of Finance',
        level: 'central',
        category: ['women', 'finance', 'child'],
        eligibility: {
            age_min: 0, age_max: 10, gender: 'female',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: false, residence: 'india',
        },
        benefit_description: 'Small savings scheme for girl child with high interest rate (currently 8.2%). Account opened in name of girl child below 10 years by parents.',
        benefit_amount: 'High interest savings + tax benefit under 80C',
        documents_required: ['Girl Child Birth Certificate', 'Parent Aadhaar Card', 'Address Proof'],
        apply_link: 'https://www.indiapost.gov.in',
        active: true,
    },
    {
        name_en: 'NREGA — Mahatma Gandhi National Rural Employment',
        name_mr: 'मनरेगा — महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार हमी',
        name_hi: 'मनरेगा — महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी',
        ministry: 'Ministry of Rural Development',
        level: 'central',
        category: ['employment'],
        eligibility: {
            age_min: 18, age_max: 120, gender: 'all',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: false, residence: 'india',
        },
        benefit_description: 'Guarantees 100 days of wage employment per year to rural households whose adult members volunteer to do unskilled manual work.',
        benefit_amount: '100 days guaranteed employment per year at ₹309/day (Maharashtra rate)',
        documents_required: ['Aadhaar Card', 'Job Card', 'Bank Account'],
        apply_link: 'https://nrega.nic.in',
        active: true,
    },
    {
        name_en: 'Stand Up India Scheme',
        name_mr: 'स्टँड अप इंडिया योजना',
        name_hi: 'स्टैंड अप इंडिया योजना',
        ministry: 'Ministry of Finance',
        level: 'central',
        category: ['employment', 'finance'],
        eligibility: {
            age_min: 18, age_max: 65, gender: 'all',
            income_limit_annual: 0, caste: ['sc', 'st', 'all'],
            bpl_required: false, residence: 'india',
        },
        benefit_description: 'Bank loans between ₹10 lakh to ₹1 crore for SC/ST and women entrepreneurs for greenfield enterprises.',
        benefit_amount: '₹10 lakh to ₹1 crore loan',
        documents_required: ['Aadhaar Card', 'PAN Card', 'Caste Certificate (for SC/ST)', 'Business Plan', 'Bank Account'],
        apply_link: 'https://www.standupmitra.in',
        active: true,
    },
    {
        name_en: 'PM Scholarship Scheme for Central Armed Police Forces',
        name_mr: 'केंद्रीय सशस्त्र पोलीस दल शिष्यवृत्ती',
        name_hi: 'केंद्रीय सशस्त्र पुलिस बल छात्रवृत्ति',
        ministry: 'Ministry of Home Affairs',
        level: 'central',
        category: ['education'],
        eligibility: {
            age_min: 17, age_max: 30, gender: 'all',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: false, residence: 'india',
        },
        benefit_description: 'Scholarship for wards and widows of Central Armed Police Forces personnel pursuing professional degree courses.',
        benefit_amount: '₹2,000 per month (girls) / ₹2,500 per month (boys)',
        documents_required: ['Aadhaar Card', 'Service Certificate of Parent', 'Admission Letter', 'Marksheet'],
        apply_link: 'https://scholarships.gov.in',
        active: true,
    },
    {
        name_en: 'Maharashtra Annasaheb Patil Loan for OBC',
        name_mr: 'अण्णासाहेब पाटील आर्थिक मागास विकास महामंडळ',
        name_hi: 'अण्णासाहेब पाटील आर्थिक विकास ऋण योजना',
        ministry: 'OBC Development Corporation, Maharashtra',
        level: 'state',
        category: ['finance', 'employment'],
        eligibility: {
            age_min: 18, age_max: 50, gender: 'all',
            income_limit_annual: 800000, caste: ['obc', 'nt', 'vjnt'],
            bpl_required: false, residence: 'maharashtra',
        },
        benefit_description: 'Loan guarantee scheme for OBC/NT/VJNT youth for starting self-employment or business. Interest subsidy provided.',
        benefit_amount: 'Loan up to ₹10 lakh with interest subsidy',
        documents_required: ['Aadhaar Card', 'Caste Certificate', 'Non-Creamy Layer Certificate', 'Income Certificate', 'Business Plan', 'Bank Account'],
        apply_link: 'https://mahavikas.maharashtra.gov.in',
        active: true,
    },
    {
        name_en: 'Beti Bachao Beti Padhao',
        name_mr: 'बेटी बचाओ बेटी पढाओ',
        name_hi: 'बेटी बचाओ बेटी पढ़ाओ',
        ministry: 'Ministry of Women and Child Development',
        level: 'central',
        category: ['women', 'child', 'education'],
        eligibility: {
            age_min: 0, age_max: 18, gender: 'female',
            income_limit_annual: 0, caste: ['all'],
            bpl_required: false, residence: 'india',
        },
        benefit_description: 'Scheme to address declining Child Sex Ratio and promote welfare and education of the girl child across India.',
        benefit_amount: 'Education support + awareness programs',
        documents_required: ['Birth Certificate', 'Aadhaar Card'],
        apply_link: 'https://wcd.nic.in/bbbp-schemes',
        active: true,
    },
];

const seedDB = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI, {
            serverSelectionTimeoutMS: 5000,
        });
        console.log('MongoDB connected for seeding.');

        // Clear existing schemes
        await Scheme.deleteMany({});
        console.log('Existing schemes cleared.');

        // Insert all schemes
        const inserted = await Scheme.insertMany(schemes);
        console.log(`✓ ${inserted.length} schemes inserted successfully.`);

        await mongoose.connection.close();
        console.log('MongoDB connection closed.');
        process.exit(0);
    } catch (error) {
        console.error('Seed error:', error.message);
        process.exit(1);
    }
};

seedDB();